name: Publish NuGet (on tag)

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Set package version from tag
        # extracts the tag name (refs/tags/v1.2.3 -> v1.2.3 -> 1.2.3)
        run: |
          echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          # remove leading 'v' if present
          echo "PACKAGE_VERSION=${GIT_TAG#v}" >> $GITHUB_ENV

      - name: Pack
        run: |
          dotnet pack src/RobustFit.Core/RobustFit.Core.csproj \
            --configuration Release \
            --output ./artifacts \
            /p:PackageVersion=${{ env.PACKAGE_VERSION }} \
            --no-build

      - name: Publish to nuget.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          echo "Pushing package..."
          dotnet nuget push ./artifacts/*.nupkg \
            --api-key $NUGET_API_KEY \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
